### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by sneazy-ibo** [Jxyme/simple-discord-rpc#14]
First of all thank you for the program, I've been searching a rpc with buttons AND timestamps for a while.

Please make the project compatible with replit so that we can host it there. Putting a token in a secret would be perfect so that account is always online without discord opened.

**Comment by Jxyme** [comment]
Discord-RPC uses the IPC protocol to communicate with the Discord application via a WebSocket. You **need** to use the tool on the **same** PC, it's simply **not** possible for it to communicate with the web browser version of Discord, or to host it on Rep.lit.

The tools that use your token and allow you to host them 24/7 are not the same. They're self bots.

Discord bots do not have the same features available, and that's why you won't find one that supports buttons etc (at the time of writing this).

Unfortunately there isn't anything I can do to support this - I also don't plan on releasing a RPC tool using the self-bot method others do.

**Comment by Jxyme** [comment]
I've updated the [README](https://github.com/Jxyme/simple-discord-rpc#-247-server-hosting-eg-replit-will-not-work-) to hopefully clear this up and to avoid further confusion, as it's something that's asked fairly often.
