### ISSUE TITLE
I have issues when adding codes into my source

### ISSUE THREAD

**Issue by Kashimaruu** [Jxyme/simple-discord-rpc#3]
Hey, I was trying to put RPC on my electron made app instance, but seems can't figure out how / why it won't work. I would gladly receive any kind of help. I've referred Githubs, Google and this git and seems can't still add these codes into mine. This repo works fine, I can set up RPC and it's up when using this git as is. Thank you!

**Comment by Jxyme** [comment]
I’m gonna go ahead and close this issue since there’s no issues with my repo/source itself, and is more so about you requiring assistance with your own project.

I understand you’ve tried searching for a solution yourself although you haven’t had much success. If you still require assistance/pointing in the right direction, feel free to reach out to me on Discord, which can be found in my GitHub bio.
